#!/usr/bin/env python

import sys
import os

PROJECT_ROOT=os.path.join(os.path.dirname(__file__), '..')
sys.path[0:0] = [ PROJECT_ROOT ]

from gevent import monkey
monkey.patch_all()

import gevent
import argparse
from pprint import pprint

from pipendencies.requirements import Requirement

def read_synchronous(f):
    with open(f) as f:
        return [ Requirement.from_line(line) for line in f.readlines() ]

def read_gevent(f):
    with open(f) as f:
        jobs = [ gevent.spawn(Requirement.from_line, line) for line in f.readlines() ]
        gevent.joinall(jobs)
        return [ job.value for job in jobs ]

parser = argparse.ArgumentParser()
parser.add_argument('file')
args = parser.parse_args()

requirements = read_gevent(args.file)
for req in requirements:
    print "Package: %s" % req.name
    print "  status:           : %s" % req.status.name
    print "  latest version    : %s" % req.latest_version
    print "  specified version : %s" % req.specified_version
    print "  available versions: %s" % req.pypi_versions
    print
